[package]
name = "rust_algorithm_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

data_structure = {path = "./data_structure"}
algorithm = {path = "./algorithm"}